// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFN1r1BehLCPUcH2NgbE0mkaFw3h3IGgQ',
    appId: '1:1087906172644:web:d2c73aaf47d674d295e6f1',
    messagingSenderId: '1087906172644',
    projectId: 'chat-app-920e5',
    authDomain: 'chat-app-920e5.firebaseapp.com',
    storageBucket: 'chat-app-920e5.appspot.com',
    measurementId: 'G-C4Y8RPXQ7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT8QXVcbdZoP83JH0Q-d9iwv-9uktgKAY',
    appId: '1:1087906172644:android:4d35f49a334e028e95e6f1',
    messagingSenderId: '1087906172644',
    projectId: 'chat-app-920e5',
    storageBucket: 'chat-app-920e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEJFe-1vsHLwvEuhZovGNkPwkO2nscTyQ',
    appId: '1:1087906172644:ios:800ba2d682d0efd695e6f1',
    messagingSenderId: '1087906172644',
    projectId: 'chat-app-920e5',
    storageBucket: 'chat-app-920e5.appspot.com',
    iosClientId: '1087906172644-f37ji4qsjforh0q2se2cidn9t9qv15ho.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEJFe-1vsHLwvEuhZovGNkPwkO2nscTyQ',
    appId: '1:1087906172644:ios:800ba2d682d0efd695e6f1',
    messagingSenderId: '1087906172644',
    projectId: 'chat-app-920e5',
    storageBucket: 'chat-app-920e5.appspot.com',
    iosClientId: '1087906172644-f37ji4qsjforh0q2se2cidn9t9qv15ho.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
